src/Modules/Admin/Http/routes.php
<?php

Route::group(['domain' => 'manager.'.env('APP_DOMAIN'), 'middleware' => 'admin', 'prefix' => '', 'namespace' => 'Modules\Admin\Http\Controllers'], function ($route) {

    $route->get('offline', 'OfflineController@index')->name('admin.offline');

    // Rotas de Autenticação
    $route->get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    $route->post('login', 'Auth\LoginController@login')->name('admin.login.post');

    $route->get('logout', 'Auth\LoginController@logout')->name('admin.logout');
    $route->post('logout', 'Auth\LoginController@logout')->name('admin.logout.post');

    $route->get('keep-alive', 'Auth\LoginController@keepalive')->name('admin.keepalive');

    // Rotas para cadastro e login via midias sociais
    //	$route->get('login/{provider}', 'Auth\LoginController@redirectToProvider')->name('admin.login.provider');
    //	$route->get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('admin.login.callback');

    // Password Reset Routes...
    $route->get('resetar-senha/', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.resetar-senha.request');
    $route->post('resetar-senha/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.resetar-senha.email');

    $route->get('resetar-senha/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.resetar-senha.reset');
    $route->post('resetar-senha/reset', 'Auth\ResetPasswordController@reset')->name('admin.resetar-senha.reset.post');

    $route->get('nova-senha/{token}', 'Auth\NewPasswordController@showForm')->name('admin.nova-senha.reset');
    $route->post('nova-senha/save', 'Auth\NewPasswordController@savePassword')->name('admin.nova-senha.save.post');


    // Rotas Privadas que precisa estar autenticado e ativo
    $route->group(['middleware' => ['authAdmin']], function ($route) {
        //  Homepage Route - Redirect based on user role is in controller.
        $route->get('/', 'AdminController@index')->name('admin.home');

        if(Request::segment(1) != 'webservice') {
            $controller = !is_null(Request::segment(1)) ? Request::segment(1) : 'admin';
            $controllerp = studly_case($controller);

            $action = !is_null(Request::segment(2)) ? Request::segment(2) : 'index';
            $method = strtolower(Request::method());

            $route->any('{slug}',
                [
                    //				'as' 	=> 	"site.{$controller}.{$action}.{$method}",
                    'uses' => "{$controllerp}Controller@{$action}"
                ]
            )->where('slug', '([A-Za-z0-9\-\_\/]+)')->name('admin.anyroute');
        }
    });
});

src/Modules/Admin/Entities/Users.php
<?php

namespace Modules\Admin\Entities;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Arr;
use Illuminate\Validation\Rule;
use Modules\Admin\Notifications\ResetPassword;
use Modules\Admin\Notifications\NewUser;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

use Modules\Admin\Repositories\DatabaseTokenRepository;
use Modules\Admin\Traits\PermissionTrait;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class Users extends Authenticatable implements AuditableContract
{
//    use Notifiable, Auditable, SoftDeletes, PermissionTrait;
    use Notifiable, Auditable, PermissionTrait;

//    protected $guard = 'admin';

    /**
     * Primary key
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * The attributes that are not mass assignable.
     *
     * @var array
     */
//    protected $guarded = ['id'];

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'login',
        'password',
        'avatar',
        'cellphone',
        'webmaster',
        'active',
    ];

    /**
     * Algumas definições
     * @var [type]
     */
//    public function getControlPermissionsAttribute()
//    {
//        return (object) [
//            'list' => 'List users'
//        ];
//    }
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'webmaster' => 'boolean',
        'active' => 'boolean',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    /**
     * Algumas definições
     * @var [type]
     */
    public function getAtributosAttribute()
    {
        return [
            'avatar' => ['titulo' => __('Avatar'), 'listar' => true, 'adicionar' => true, 'editar' => true, 'uploadpath' => "users/{$this->id}/avatar/"],

            'name' => ['titulo' => __('Name'), 'listar' => true, 'adicionar' => true, 'editar' => true, 'trocarsenha' => 'false'],
            'login' => ['titulo' => __('Login'), 'listar' => true, 'adicionar' => true, 'editar' => true, 'trocarsenha' => 'false'],
            'email' => ['titulo' => __('E-mail'), 'listar' => true, 'adicionar' => true, 'editar' => true, 'trocarsenha' => 'false'],
            'cellphone' => ['titulo' => __('Cellphone'), 'listar' => true, 'adicionar' => true, 'editar' => true, 'trocarsenha' => 'false'],
            'active' => ['titulo' => __('Active'), 'listar' => false, 'adicionar' => true, 'editar' => true, 'trocarsenha' => 'false'],

            'password' => ['titulo' => __('Password'), 'listar' => false, 'adicionar' => true, 'editar' => false, 'trocarsenha' => true],
        ];
    }

    /**
     * Regras de validação
     * @var array
     */
    public function getRulesAttribute()
    {
        // Parametros adicionais dinamicos vindos da url
        foreach (request()->segments() as $key => $value) {
            if ($key > 2) {
                ${request()->segment($key)} = request()->segment($key + 1);
            }
        }
        if (!isset($id)) {
            $id = null;
        }

        return [
            'nome' => 'required|min:2',
            'login' => [
                'regra' => [
                    'required',
                    'min:4',
                    Rule::unique('users', 'login')->ignore($id)
                ]
            ],
            'email' => [
                'regra' => [
                    'required',
                    'min:3',
                    'email',
                    Rule::unique('users', 'email')->ignore($id)
                ]
            ],
            'active' => 'boolean',
        ];
    }

    /**
     * Mensagens de validação
     * @return array
     */
    public function messages()
    {
        return [
            'name.required' => __("validation.required", ['attribute' => __('Name')]),
            'login.required' => __("validation.required", ['attribute' => 'Login']),
            'email.required' => __("validation.required", ['attribute' => 'E-mail']),
            'password.required' => __("validation.required", ['attribute' => 'Senha']),

            'name.min' => __("validation.min", ['attribute' => __('Name')]),
            'login.min' => __("validation.min", ['attribute' => 'Login']),
            'email.min' => __("validation.min", ['attribute' => 'E-mail']),
            'password.min' => __("validation.min", ['attribute' => 'Senha']),

            'email.email' => __("validation.email", ['attribute' => 'E-mail']),

            'password.confirmed' => __("validation.confirmed", ['attribute' => 'Senha']),

            'active.boolean' => __("validation.required", ['attribute' => 'Ativo']),

            'login.unique' => __("validation.unique", ['attribute' => 'Login']),
            'email.unique' => __("validation.unique", ['attribute' => 'E-mail']),
        ];
    }

    public function getAvatarImagemAttribute()
    {
        $retorno = null;
        if (!empty($this->avatar)) {
            $retorno = $this->atributos['avatar']['uploadpath'] . $this->avatar;
        }

        return $retorno;
    }

    /**
     * @param $value
     */
    public function setPasswordAttribute($value)
    {
        if (!is_null($value)) {
            $data = bcrypt($value);
            $this->attributes['password'] = $data;
        }
    }

    /**
     * @param $value
     */
    public function setSenhaAttribute($value)
    {
        if (!is_null($value)) {
            $data = bcrypt($value);
            $this->attributes['password'] = $data;
        }
    }

    /**
     * Send the password reset notification.
     *
     * @param  string $token
     *
     * @return void
     */
    public function sendPasswordResetNotificationNew($token, $user)
    {
        $notification = new ResetPassword($token, $user);

        // Teste - descomentar até o dd
//     $novo_markdown = [
//     	'theme' => 'padrao',
//     	'paths' => [
//     		resource_path('../Modules/Admin/Resources/views/mail'),
//     	],
//     ];
//     $markdown = new \Illuminate\Mail\Markdown(view(), $novo_markdown);
//     $data = $notification->teste() -> toArray();
//     // dump( $data );
//     echo $markdown->render('admin::notifications.email', $data);
//     dd();

        config(
            [
                'mail.markdown.theme' => 'padrao',
                'mail.markdown.paths' => [
                    resource_path('../Modules/Admin/Resources/views/mail'),
                ],
            ]
        );

        $this->notify($notification);
    }

    /**
     * Send the password reset notification.
     *
     * @param  string $token
     *
     * @return void
     */
    public function sendNewPasswordNotification($token, $user)
    {
        $notification = new NewUser($token, $user);

        // Teste - descomentar até o dd
//     $novo_markdown = [
//     	'theme' => 'padrao',
//     	'paths' => [
//     		resource_path('../Modules/Admin/Resources/views/mail'),
//     	],
//     ];
//     $markdown = new \Illuminate\Mail\Markdown(view(), $novo_markdown);
//     $data = $notification->teste() -> toArray();
//     // dump( $data );
//     echo $markdown->render('admin::notifications.email', $data);
//     dd();

        config(
            [
                'mail.markdown.theme' => 'padrao',
                'mail.markdown.paths' => [
                    resource_path('../Modules/Admin/Resources/views/mail'),
                ],
            ]
        );

        $this->notify($notification);
    }

    // Trazer os grupos que possuem esas permission

    /**
     * Get the user for the given credentials.
     *
     * @param  array $credentials
     *
     * @return \Illuminate\Contracts\Auth\CanResetPassword
     *
     * @throws \UnexpectedValueException
     */
    public function getUser(array $credentials)
    {
        $credentials = Arr::except($credentials, ['token']);

        $user = static::where('email', $credentials['email'])->first();

        if ($user && !$user instanceof CanResetPasswordContract) {
            throw new \UnexpectedValueException('User must implement CanResetPassword interface.');
        }

        return $user;
    }

    public function groups()
    {
        return $this->belongsToMany(
            PermissionsGroup::class,
            'user_permissions_group',
            'user_id',
            'permissions_group_id'
        )->withTimestamps()->withPivot('user_id', 'permissions_group_id');
    }

    // Traz as permissões deste grupo
    public function permissions()
    {
        $permission = collect(
            json_decode($this->getAttributes()['permissions'])
        );

        return $permission;
    }

    /**
     * Seta relacionamentos
     */
    public $relacionamentos = [
    ];

    public function getAcaoAttribute()
    {
        return [
            'groups' => [
                'html' => '
                    <a class="dropdown-item" title="' . __('Groups Permissions') . '" href="' . route('admin.anyroute', ['user_groups/index/user_id']) . '/{$id}">
                      ' . __('Groups Permissions') . '
                    </a>
                '
            ],

            /*'permissions' => [
                'html' => '
                    <a class="dropdown-item open-form-sidebar" title="' . __('Permissions') . '" href="' . route('admin.anyroute', ['users/permissions/id']) . '/{$id}">

src/Modules/Admin/Resources/views/users/form-permissions.blade.php
@extends('admin::layouts.master-clear')

@section('conteudo')
  <div class="m-content">
    <div class="row">
      <div class="col-lg-12">
        <div class="m-portlet">
          {!! Form::model($FormModel, ['url' => $url, 'class' => 'm-form m-form--label-align-right form-geral', 'files' => true]) !!}


          <div class="form-group m-form__group row col m-0 baseClass">
            {!! Form::label('permissions', __('Permissions Allowed'), ['class' => 'col-2 col-form-label']) !!}
            <div class="clearfix"></div>
            <div class="col-12 form-group m-form__group">
              <div class="col-8 col-lg-4">
                <div class="input-group">
                  <input type="text" name="search" class="form-control m-input" placeholder="{!! __('Search for...') !!}">
                  <div class="input-group-append">
                    <button class="btn btn-secondary clear" type="reset">{!! __('Clear') !!}</button>
                    <button class="btn btn-secondary search" type="button">{!! __('Search') !!}</button>
                  </div>
                </div>

              </div>
              <br>
            </div>

            <div class="col-12">
              <div id="permissions" class="tree-demo" role="tree" aria-multiselectable="true" tabindex="0" aria-activedescendant="j3_3" aria-busy="false">
                <ul>
                  <li id="todas_permissioes" data-jstree='{"opened":true}' data-inputname="all_permissions" data-inputvalue="all">
                    {{--<input type="checkbox" name="permission_all"> --}}
                    {!! __('All permissions') !!}
                    <ul>
                      @foreach ($permissions as $key => $permission)
                        <li data-inputname="permission_allowed[]" data-inputvalue="{!! $permission->id !!}" data-inputchecked="{!! (!is_null($FormModel->permissions()->where('id', $permission->id)->first()))? true : false!!}">
                          {{--<input type="checkbox" name="permission_{!! $permission->id !!}" value="{!! $permission->id !!}">--}}
                          {!! $permission->name !!}
                        </li>
                      @endforeach
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          <div class="form-group m-form__group row col m-0  baseClass">
            {!! Form::label('permissions', __('Permissions Not Allowed'), ['class' => 'col-2 col-form-label']) !!}
            <div class="clearfix"></div>
            <div class="col-12 form-group m-form__group">
              <div class="col-8 col-lg-4">
                <div class="input-group">
                  <input type="text" name="search" class="form-control m-input" placeholder="{!! __('Search for...') !!}">
                  <div class="input-group-append">
                    <button class="btn btn-secondary clear" type="reset">{!! __('Clear') !!}</button>
                    <button class="btn btn-secondary search" type="button">{!! __('Search') !!}</button>
                  </div>
                </div>
              </div>
              <br>
            </div>

            <div class="col-12">
              <div id="permissions_not" class="tree-demo" role="tree" aria-multiselectable="true" tabindex="0" aria-activedescendant="j3_3" aria-busy="false">
                <ul>
                  <li id="todas_permissioes" data-jstree='{"opened":true}' data-inputname="all_permissions" data-inputvalue="all">
                    {{--<input type="checkbox" name="permission_all"> --}}
                    {!! __('All permissions') !!}
                    <ul>
                      @foreach ($permissions as $key => $permission)
                        <li data-inputname="permission_allowed[]" data-inputvalue="{!! $permission->id !!}" data-inputchecked="{!! (!is_null($FormModel->permissions()->where('id', $permission->id)->first()))? true : false!!}">
                          {{--<input type="checkbox" name="permission_{!! $permission->id !!}" value="{!! $permission->id !!}">--}}
                          {!! $permission->name !!}
                        </li>
                      @endforeach
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {!! Form::botoesform($pagina, true, true, true, false) !!}

          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
@stop

@push('line-js')
  <script>
    $(function () {
      var tree = $('.tree-demo');

      tree.jstree({
        'plugins': ["html_data", "search", "checkbox", "realcheckboxes", "types"],
        'core': {
          "themes": {
            "responsive": false
          }
        },
        "types": {
          "default": {
            "icon": "far fa-list-alt m--font-primary"
          }
        }
      });

      tree.on('ready.jstree', function(e, data){
          $('#permissions li').each(function() {
            let element = $(this),
              inputchecked = (element.data('inputchecked'))? element.data('inputchecked') : false,
              inputname = (element.data('inputname'))? element.data('inputname') : false,
              inputvalue = (element.data('inputvalue'))? element.data('inputvalue') : false
            ;

            element.find('> .jstree-icon.jstree-checkbox').html('<input type="checkbox" class="jstree-checkbox">');

            input = element.find('input[type="checkbox"]:first');

            if(inputvalue){
              input.val(inputvalue);
            }
            if(inputname){
              input.attr('name', inputname);
            }
            if(inputchecked){
              input.prop('checked', true);
              tree.jstree('check_node', $(this));
            }

          });
      });

      tree.on('search.jstree', function (e, data) {
        if((data.res).length <= 0){
          parent.swal({
            text: '{!! __('Permission not found') !!}',
            icon: "error",
          });
        }
      });

      var to = setTimeout(function () {}, 100);
      var search = $('[name="search"]');

      search.on('keydown', function(e){
        if(e.keyCode == 13)
        {
          $(this).parent().find('button.search').trigger("click");
          return false;
        }
      });

      $('button.search').on('click', function () {
        clearTimeout(to);
        to = setTimeout(function () {
          var v = search.val();
          console.log($(this).parents('.baseClass').find('.tree-demo'))
          $(this).parents('.baseClass').find('.tree-demo').jstree(true).search(v, false, true);
        }, 250);
      });

      $('button.clear').on('click', function () {
        clearTimeout(to);
        $(this).parents('.baseClass').find('.tree-demo').jstree(true).clear_search();
        search.val('');
      });

    });
  </script>
@endpush

src/Modules/Admin/Resources/views/users/form.blade.php
@extends('admin::layouts.master-clear')

@section('conteudo')
  <div class="m-grid__item m-grid__item--fluid m-wrapper">

    @if(!empty($FormModel))
      <div class="m-portlet m-portlet--full-height m-0">
        <div class="m-portlet__body p-0">
          <div class="m-card-profile">
            <div class="m-card-profile__title m--hide">
              {!! __('Perfil') !!}
            </div>
            <div class="m-card-profile__pic">
              <div class="m-card-profile__pic-wrapper">
                @if((!empty($FormModel->avatar_imagem) && file_exists(public_path('uploads/'.$FormModel->avatar_imagem))))
                  <img src="{{ route('thumbfit',[ 80, 80, $FormModel->avatar_imagem, 'ffffff', true]) }}"
                       alt="{!! $FormModel->nome !!}">
                @else
                  <img src="metronic/app/media/img/users/user4.jpg" alt=""/>
                @endif
              </div>
            </div>
            <div class="m-card-profile__details">
              <span class="m-card-profile__name">{!! $FormModel->nome !!}</span>
              <a href="" class="m-card-profile__email m-link">{!! $FormModel->email !!}</a>
            </div>
          </div>
        </div>
      </div>
    @endif

    <div class="m-portlet m-portlet--full-height m-portlet--tabs">
      <div class="m-portlet__head pt-0">
        <div class="m-portlet__head-tools m-0">
          <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary"
              role="tablist">
            <li class="nav-item m-tabs__item">
              <a class="nav-link m-tabs__link active" data-toggle="tab"
                 href="#atualizar_cadastro" role="tab">
                <i class="flaticon-share m--hide"></i>
                @if ($action != 'edit')
                  {!! __('Criar Um Novo perfil') !!}
                @else
                  {!! __('Editar Perfil') !!}
                @endif
              </a>
            </li>
            @if ($action == 'edit')
              <li class="nav-item m-tabs__item">
                <a class="nav-link m-tabs__link" data-toggle="tab"
                   href="#atualizar_senha" role="tab">
                  <i class="flaticon-share m--hide"></i>
                  Atualizar Senha
                </a>
              </li>
            @endif
          </ul>
        </div>
      </div>
      <div class="tab-content">
        <div class="tab-pane active" id="atualizar_cadastro">
          {!! Form::model($FormModel, ['url' => $url, 'class' => 'm-form m-form--fit m-form--label-align-right form-geral', 'files' => true]) !!}

          <div class="form-group m-form__group row">
            {!! Form::label('', __('Avatar'), [ 'class' => 'col-2 col-form-label' ]) !!}
            <div class="col-7">
              @if( !empty($FormModel->avatar) )
                <label for="avatar"
                       class="btn btn-outline-accent m-btn m-btn--icon m-btn--outline-2x m-btn--pill m-btn--air has-tip top file-arquivo float-left mr-2">
                  <span>

                    <span>{!! __('Selecione um avatar') !!}</span>
                    {!! Form::fileHTML('avatar', null, ['id' => 'avatar', 'class' => 'd-none', 'style' => 'margin-bottom:0;']) !!}
                  </span>
                </label>

                <a href="{{ route('thumb',[ 0, 0, $FormModel->avatar_imagem ]) }}"
                   class="btn btn-outline-accent m-btn m-btn--icon m-btn--outline-2x m-btn--pill m-btn--air has-tip top viewfile">
                  {!! __('Show avatar') !!}
                </a>

                <a
                  data-ajax="{{ url("{$pagina}/deletararquivo/id/{$FormModel -> id}/campo/avatar/path/users/path1/{$FormModel->id}/path2/avatar") }}"
                  data-texto="Deseja remover a avatar?" data-excluir=""
                  data-remover=".itemavatar .deletfile, .itemavatar .viewfile" title="Excluir"
                  class="deletfile btn btn-outline-danger m-btn m-btn--icon m-btn--icon-only m-btn--custom m-btn--outline-2x m-btn--pill m-btn--air">
                  <i aria-hidden="true" class="fa fa-times"></i>
                </a>
              @else
                <label for="avatar"
                       class="btn btn-outline-accent m-btn m-btn--icon m-btn--outline-2x m-btn--pill m-btn--air has-tip top file-arquivo">
                  <span>

                    <span>{!! __('Selecione um avatar') !!}</span>
                    {!! Form::fileHTML('avatar', null, ['id' => 'avatar', 'class' => 'd-none', 'style' => 'margin-bottom:0;']) !!}
                  </span>
                </label>
              @endif
            </div>
          </div>

          <div class="form-group m-form__group row">
            {!! Form::label('name', 'Nome', ['class' => 'col-2 col-form-label']) !!}
            <div class="col-7">
              {!! Form::text('name', null, ['class' => 'form-control m-input', 'required' => 'true']) !!}
            </div>
          </div>

          <div class="form-group m-form__group row">
            {!! Form::label('cellphone', 'Telefone', ['class' => 'col-2 col-form-label']) !!}
            <div class="col-7">
              {!! Form::text('cellphone', null, ['class' => 'form-control m-input mask-intl-phone']) !!}
            </div>
          </div>

          <div class="form-group m-form__group row">
            {!! Form::label('login', 'Login', ['class' => 'col-2 col-form-label']) !!}
            <div class="col-7">
              {!! Form::text('login', null, ['class' => 'form-control m-input', 'required' => 'true']) !!}
            </div>
          </div>

          <div class="form-group m-form__group row">
            {!! Form::label('email', 'E-mail', ['class' => 'col-2 col-form-label']) !!}
            <div class="col-7">
              {!! Form::email('email', null, ['class' => 'form-control m-input', 'required' => 'true']) !!}
            </div>
          </div>

          {{--@if ($action != 'edit')
            <div class="form-group m-form__group row">
              {!! Form::label('password', 'Nova Senha', ['class' => 'col-2 col-form-label']) !!}
              <div class="col-7">
                {!! Form::password('password', array('class' => 'form-control m-input', 'required' => 'true')) !!}
              </div>
            </div>

            <div class="form-group m-form__group row">
              {!! Form::label('password_confirmation', 'Confirmar Nova Senha', ['class' => 'col-2 col-form-label']) !!}
              <div class="col-7">
                {!! Form::password('password_confirmation', array('class' => 'form-control m-input', 'required' => 'true')) !!}
              </div>
            </div>
          @endif--}}

          <div class="form-group m-form__group row">
            {!! Form::label('', __('Ativo?'), ['class' => 'col-2 col-form-label']) !!}
            <div class="col-7">
              {!! Form::statuscor('active', ((!empty($FormModel->active) && !is_null($FormModel->active))? $FormModel->active : null) ) !!}
            </div>
          </div>

          {!! Form::botoesform($pagina, $cancelar = true, $salvarecontinuar = false, $salvar = true, $limpar = false, $options = [  ]) !!}
          {!! Form::close() !!}
        </div>

        @if ($action == 'edit')
          <div class="tab-pane" id="atualizar_senha">
            {!! Form::model($FormModel, ['url' => route('admin.anyroute', [ 'slug' => $urlpass ]), 'class' => 'm-form m-form--fit m-form--label-align-right form-geral', 'autocomplete' => 'off']) !!}

            <div class="form-group m-form__group row">
              {!! Form::label('password', 'Nova Senha', ['class' => 'col-2 col-form-label']) !!}
              <div class="col-7">
                {!! Form::password('password', array('class' => 'form-control m-input', 'required' => 'true')) !!}
              </div>
            </div>

            <div class="form-group m-form__group row">
              {!! Form::label('password_confirmation', 'Confirmar Nova Senha', ['class' => 'col-2 col-form-label']) !!}
              <div class="col-7">
                {!! Form::password('password_confirmation', array('class' => 'form-control m-input', 'required' => 'true')) !!}
              </div>
            </div>


            {!! Form::botoesform($pagina, $cancelar = true, $salvarecontinuar = true, $salvar = true, $limpar = false, $options = [ 'texto-salvar' => ' Alterar senha ', 'texto-salvar-continuar' => ' Alterar senha e continuar editando ' ]) !!}
            {!! Form::close() !!}
          </div>
        @endif

      </div>
    </div>

  </div>
@stop

@push('line-js')
  <style>
    .internal-form .m-portlet {
      margin-bottom: 0 !important;
    }

    .m-portlet.m-portlet--full-height {
      position: relative;
    }

    .m-portlet .m-portlet__foot:not(.m-portlet__no-border) {
      position: fixed;
    }
  </style>
@endpush